language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: FMV6r7wSPHk05EEj9sQCgO5RIde+OyFUZCe5+62G/dbI66gy1kSOqnGStXiLBx7NRqiNQVCDs/+pF7PdvbTVcQpPgkXyzkuhvd6rOyFqekEO7iY3MHDG9za0RpkTPILxYRVFp4S8Px8DtFpUjyVAZzbhVtk36yWEAU58Z0bEK6u7y5D27ptwyMVzyha14AtFJ0iuRkCF0LHWcr8oef+iU36FEbjk3b5Sowl9Lz6DrawZeCBsKLYnre2aBe+U+LEP+aDc3MTgT6V+gEh7l1fAI7lbgcaxB2nMT6gbHrX8Zj0iuQEvVCyJvW41TSUvd5R5JA8glAGFBJ6TmDRPZMT3QUeoMDalyKGmRG+GTfR7L0iBtBjDWq8qOFnl6ZwvcKtm8u+yoMDOJHZscI31Yszu4vzaapQCLQvt2ZqLVVo6J/x/X/4aV/BLR/50j4Y5AOJOjDcnOwAYNVJarcSPzKv/FFpbIuA87/OH/PoZB/jqBWH8CjeiI++bblhwNPelMygkDr/aoPih6yvk/KpkabaU79XuRQMHZ7NGnIIyH5cTa19SQzbzPrKlFIp0g61SVYKlVB7A9/eAZhOwkatGjaBQZTmCPP81X7yl6kp+y2cWlq6Ia4Qkxfy6ZsHjs6Htlexqti7K0wGiYQXyBOXrG1oE49yAsqAis9mOdjw4t3Zvav0=
  - secure: P1UlLS+ozWiaQeSNPCr5RzqTzybVZZqb9S46y85TQI9edfqgoAZqJJXNyed+VqKGMFmETK1RnYSInyLqBh9q/l4VLQIhD/91NER8iCpo0JSIyR70DSwF0wtXpuS/gUg1OAV/wpz0iMzank2F0PX/+iojlqwdoypqgxHEgkCD94C6uDTwJZYVt5rC1b+LdTF2dn4Z58e91PEOhZ4fDs3iT5iZ5g4OJit9ytzEHcE1kqRAAf3fZkxR2NU/5yBKc46bcHjJHdncpHXmcTJzjYxxNSx3H3HzqtNFsREl7BlrhxXapeRZ8z86j2IEm5EW8XpdGZFRoJkfu1i5C5FDBnXSZUjJ+s+dcHeqJDDZjK7sRhqGMyfBNh3x6lPCetFHucB2a1Geht3fCnW883Ob31XK5Gmwm5VREq8rzZH19B7lzXHv6eLALxHs32BRa7MXNv1Mdh/Kd26zCrJi4rnPvDuMlDRlpBryYmAtqu5Vh0p1lDG6xcJofqgz1u50a++g7CnrOxiSQp88c06LZg5huiHW0mBKu6yc/v0ypylEFCch+np2gR/DlWrAkgWVQckIdorj0EL6XiKwJwG3ZYbqw7xRVfihK75INK9zBL6hQ7EvlSAVwPEltlI/+31zBXihGPtjty2YZLRStiW/YKIVihUsSqJHntS9yVCSSRML8G9tZkw=
